name: release build, test & publish

on: push


jobs:
  library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: ./helper.sh deps
    - name: run tests
      run: ./helper.sh test
    - name: build code
      run: ./helper.sh build
    - name: publish package to npm
      if: ${{ startsWith(github.ref_name, 'release_') }}
      run: ./helper.sh publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  service:
    needs: library
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'feature_spa') }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: ./helper.sh test_infra reqs
    - run: ./helper.sh test_infra on
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: ./helper.sh test_ui reqs
    - run: ./helper.sh test_ui build
    - run: ./helper.sh test_ui config
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: ./helper.sh test_ui upload
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
