name: release build, test & publish

on:
  push:
    branches: [ development, release_*, feature_* ]

jobs:
  library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: ./helper.sh lib deps
    - name: build code
      run: ./helper.sh lib build
    - name: run tests
      run: ./helper.sh lib test
    - name: publish package to npm
      # if: ${{ startsWith(github.ref_name, 'release_') }}
      run: ./helper.sh lib publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    needs: library
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'release_') }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: ./helper.sh infra reqs
    - run: ./helper.sh infra deps
    - run: ./helper.sh infra on
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



    
